steps:
  # running docker-compose
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/able-rain-354612/sc2rep-fastapi']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'fast-api', '--image', 'gcr.io/able-rain-354612/sc2rep-fastapi', '--region', 'global']
images:
  - gcr.io/able-rain-354612/sc2rep-fastapi