steps:
  # running docker-compose
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'workspace_app:latest',
    'gcr.io/able-rain-354612/sc2rep_fastapi:latest']
images: ['global-docker.pkg.dev/able-rain-354612/sc2rep_fastapi:latest']
