version: '3.1'

services:
  mongo:
    image: mongo:4.2
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"

  backend:
    build: ./
    container_name: sc2reporter-backend
    restart: unless-stopped
    platform: linux/amd64
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017

  frontend:
    build: ./frontend
    container_name: sc2reporter-frontend
    ports:
      - '3000:3000'
    environment:
      - 'REACT_APP_BACKEND_URL=https://8000'
    volumes:
      - ./frontend:/app
      - ./app/node_modules