version: "3.1"
services:
  fastapi:
    build: ./backend/.
    container_name: sc2reporter-api
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      - mongo_seed
    restart: "unless-stopped"
    links: 
      - mongodb
    env_file:
      - backend/docker.env
  
  mongodb:
    image: mongo:4.4.6
    platform: linux/amd64
    hostname: mongodb
    restart: unless-stopped
    ports: 
     - "27017:27017"

  mongo_seed:
    build: ./mongo-seed/.
    command:
      - /mongo-seed/import.sh
    links: 
      - mongodb
    depends_on:
      - mongodb
      
  mongo-express:
    image: mongo-express:0.54.0
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
    - ME_CONFIG_MONGODB_SERVER=mongodb
    - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb

  frontend:
    build: ./frontend/.
    container_name: sc2reporter-frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - 'REACT_APP_BACKEND_URL=http://0.0.0.0:8000'
    depends_on:
      - fastapi