version: "3.1"
services:
  fastapi:
    build: ./sc2rep-api/.
    platform: linux/amd64
    ports:
      - "8000:8000"
    depends_on:
      - mongo_seed
    restart: "unless-stopped"
    links: 
      - mongodb
    env_file:
      - sc2rep-api/docker.env
  
  mongodb:
    image: mongo
    hostname: mongodb
    restart: unless-stopped
    ports: 
     - "27017:27017"

  mongo_seed:
    build: ./mongo-seed/.
    command:
      - /mongo-seed/import.sh
    links: 
      - mongodb
    depends_on:
      - mongodb
