version: '3.1'

services:

  mongo:
    image: mongo:4.2
    hostname: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"


  app:
    build: ./
    restart: unless-stopped
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8000:8000"
