version: '3.1'

services:

  mongo:
    image: mongo:4.2
    restart: unless-stopped
    hostname: sarscov2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - ./data/

  app:
    build: ./
    restart: unless-stopped
    depends_on:
      - mongo
    links:
      - mongo


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
