name: Deploy frontend to Firebase Hosting on merge
defaults:
  run:
    working-directory: ./frontend
'on':
  push:
    branches:
      - add-react-app
    paths:
      - frontend/**
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install
      - name: Run lint check
        run: yarn lint
      - name: Run Stylelint check
        run: npx stylelint "**/*.css"
      - name: Test
        run: yarn test --passWithNoTests
      - name: Build
        run: yarn build
        env:
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: sc2reporter
          entryPoint: "./frontend"